{% set version = "1.10.13" %}

package:
  name: ant-split
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/ant/source/apache-ant-{{ version }}-src.tar.gz
  sha256: da006f4c888d41d0f3f213565e48aeff73e4d8a6196e494121d8da1e567a8406

build:
  number: 0

requirements:
  build:
    - openjdk  # [build_platform != target_platform]
  host:
    - openjdk
  run:
    - openjdk

outputs:
  - name: ant
    script: build-pkg.sh  # [not win]
    script: build-pkg.bat  # [win]
    requirements:
      host:
        - openjdk
      run:
        - openjdk
    test:
      commands:
        - ant -help
        - ant -version

  # compatibility output for previous name of package in conda-forge
  - name: apache-ant
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('ant', exact=True) }}
    test:
      commands:
        - ant -help
        - ant -version

about:
  home: https://ant.apache.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: Apache Ant is a Java library and command-line tool that mainly helps building software.
  dev_url: https://github.com/apache/ant

extra:
  recipe-maintainers:
    - ThejashwiniSwamy
    - h-vetinari
  feedstock-name: apache-ant
