{% set name = "apache-ant" %}
{% set version = "1.10.11" %}
{% set sha256 = "c44d71e07e240eaab638d1da96f2038f84dcc1f245656f03e040a69603ca5b39" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/ant/source/{{ name }}-{{ version }}-src.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  host:
    - openjdk >=8,<9

  run:
    - openjdk >=8,<9

test:
  commands:
    - ant -help
    - ant -version

about:
  home: https://ant.apache.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: Apache Ant is a Java library and command-line tool that mainly helps building software.

extra:
  recipe-maintainers:
    - ThejashwiniSwamy
